#!/bin/bash -i

cd ~
clear


repo="dotfile"
url="https://github.com/suchdatums/$repo"
git clone --depth=1 $url
rm -rf ./$repo/.git
# move file out of repo folder to <here>
mv -f ./$repo/* .


# make them dot files
mv -f bash_aliases .bash_aliases
mv -f getdot .getdot
mv -f helpdot .helpdot
mv -f installdot .installdot
mv -f tmux.conf .tmux.conf

echo -e "
>> RUN this to refresh: \e[0;91m source .bash_aliases \e[0m\n
"
